from .account import desativar_conta, perfil, registro, trocar_senha, verificar_email
from .admin_views import (
    admin_usuario_create,
    admin_usuario_edit,
    admin_usuarios,
    aprovacoes,
    aprovar_item,
    categoria_create,
    categoria_delete,
    categoria_list,
    categoria_update,
    local_create,
    local_delete,
    local_list,
    local_update,
)
from .claims import solicitacao_create, solicitacao_detail, solicitacao_validar
from .dashboard import dashboard, meus_registros
from .items import (
    objeto_encontrado_create,
    objeto_encontrado_delete,
    objeto_encontrado_detail,
    objeto_encontrado_update,
    objeto_perdido_mark_found,
    objeto_perdido_create,
    objeto_perdido_delete,
    objeto_perdido_detail,
    objeto_perdido_update,
)
from .public import encontrados_publico, home, perdidos_publico

__all__ = [
    'admin_usuario_create',
    'admin_usuario_edit',
    'admin_usuarios',
    'aprovacoes',
    'aprovar_item',
    'categoria_create',
    'categoria_delete',
    'categoria_list',
    'categoria_update',
    'dashboard',
    'desativar_conta',
    'encontrados_publico',
    'home',
    'local_create',
    'local_delete',
    'local_list',
    'local_update',
    'meus_registros',
    'objeto_encontrado_create',
    'objeto_encontrado_delete',
    'objeto_encontrado_detail',
    'objeto_encontrado_update',
    'objeto_perdido_mark_found',
    'objeto_perdido_create',
    'objeto_perdido_delete',
    'objeto_perdido_detail',
    'objeto_perdido_update',
    'perfil',
    'perdidos_publico',
    'registro',
    'trocar_senha',
    'verificar_email',
    'solicitacao_create',
    'solicitacao_detail',
    'solicitacao_validar',
]
