# Generated by Django 4.2.29 on 2026-03-28 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Local')),
                ('predio', models.CharField(max_length=100, verbose_name='Prédio')),
                ('andar', models.CharField(blank=True, max_length=20, verbose_name='Andar')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['predio', 'nome'],
                'unique_together': {('nome', 'predio')},
            },
        ),
        migrations.CreateModel(
            name='ObjetoEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição detalhada')),
                ('data_encontrado', models.DateField(verbose_name='Data que encontrou')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reivindicado', 'Reivindicado'), ('devolvido', 'Devolvido ao dono'), ('encerrado', 'Encerrado')], default='disponivel', max_length=15, verbose_name='Status')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='encontrados/', verbose_name='Imagem')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_encontrados', to='core.categoria', verbose_name='Categoria')),
                ('local_encontrado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_encontrados', to='core.local', verbose_name='Local onde encontrou')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_encontrados', to=settings.AUTH_USER_MODEL, verbose_name='Encontrado por')),
            ],
            options={
                'verbose_name': 'Objeto Encontrado',
                'verbose_name_plural': 'Objetos Encontrados',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='ObjetoPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição detalhada')),
                ('data_perda', models.DateField(verbose_name='Data da perda')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('status', models.CharField(choices=[('aberto', 'Aberto - Procurando'), ('encontrado', 'Encontrado'), ('encerrado', 'Encerrado')], default='aberto', max_length=15, verbose_name='Status')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perdidos/', verbose_name='Imagem')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_perdidos', to='core.categoria', verbose_name='Categoria')),
                ('local_perdido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_perdidos', to='core.local', verbose_name='Local onde perdeu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_perdidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Objeto Perdido',
                'verbose_name_plural': 'Objetos Perdidos',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPosse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_comprovacao', models.TextField(help_text='Descreva características do objeto que comprovem que é seu.', verbose_name='Descrição de comprovação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10, verbose_name='Status')),
                ('resposta_admin', models.TextField(blank=True, verbose_name='Resposta do administrador')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da resposta')),
                ('objeto_encontrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.objetoencontrado', verbose_name='Objeto encontrado')),
                ('objeto_perdido', models.ForeignKey(blank=True, help_text='Opcional: vincule ao seu registro de perda, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='core.objetoperdido', verbose_name='Registro de perda relacionado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Posse',
                'verbose_name_plural': 'Solicitações de Posse',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno / Usuário Comum'), ('funcionario', 'Funcionário'), ('admin', 'Administrador')], default='aluno', max_length=15)),
                ('matricula', models.CharField(blank=True, max_length=20, verbose_name='Matrícula')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
