# Generated by Django 4.2.29 on 2026-04-20 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Local')),
                ('predio', models.CharField(max_length=100, verbose_name='Prédio')),
                ('andar', models.CharField(blank=True, max_length=20, verbose_name='Andar')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['predio', 'nome'],
                'unique_together': {('nome', 'predio')},
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], max_length=10, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição detalhada')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da ocorrência')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('ativo', 'Ativo'), ('reivindicado', 'Reivindicado'), ('devolvido', 'Devolvido'), ('encerrado', 'Encerrado')], default='pendente', max_length=15, verbose_name='Status')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='objetos/', verbose_name='Imagem')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='core.categoria', verbose_name='Categoria')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='core.local', verbose_name='Local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPosse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_comprovacao', models.TextField(help_text='Descreva características do objeto que comprovem que é seu.', verbose_name='Descrição de comprovação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10, verbose_name='Status')),
                ('resposta_admin', models.TextField(blank=True, verbose_name='Resposta do administrador')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da resposta')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.objeto', verbose_name='Objeto encontrado')),
                ('objeto_perdido', models.ForeignKey(blank=True, help_text='Opcional: vincule ao seu registro de perda, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_como_perdido', to='core.objeto', verbose_name='Registro de perda relacionado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Posse',
                'verbose_name_plural': 'Solicitações de Posse',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuário'), ('admin', 'Administrador')], default='usuario', max_length=15)),
                ('matricula', models.CharField(blank=True, max_length=20, verbose_name='Matrícula')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_verificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Verificação',
                'verbose_name_plural': 'Códigos de Verificação',
            },
        ),
        migrations.AddConstraint(
            model_name='solicitacaoposse',
            constraint=models.UniqueConstraint(fields=('solicitante', 'objeto'), name='unique_solicitante_objeto'),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('matricula', ''), _negated=True), fields=('matricula',), name='unique_perfil_matricula_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('telefone', ''), _negated=True), fields=('telefone',), name='unique_perfil_telefone_not_blank'),
        ),
    ]
