# Generated by Django 4.2.29 on 2026-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoencontrado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('disponivel', 'Disponível'), ('reivindicado', 'Reivindicado'), ('devolvido', 'Devolvido ao dono'), ('encerrado', 'Encerrado')], default='pendente', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='objetoperdido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aberto', 'Aberto - Procurando'), ('encontrado', 'Encontrado'), ('encerrado', 'Encerrado')], default='pendente', max_length=15, verbose_name='Status'),
        ),
    ]
