# Generated by Django 4.2.29 on 2026-04-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('ativo', 'Ativo'), ('reivindicado', 'Reivindicado'), ('devolvido', 'Devolvido')], default='pendente', max_length=15, verbose_name='Status'),
        ),
    ]
