# Generated by Django 4.2.29 on 2026-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_objetoencontrado_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('matricula', ''), _negated=True), fields=('matricula',), name='unique_perfil_matricula_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('telefone', ''), _negated=True), fields=('telefone',), name='unique_perfil_telefone_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaoposse',
            constraint=models.UniqueConstraint(fields=('solicitante', 'objeto_encontrado'), name='unique_solicitante_objeto_encontrado'),
        ),
    ]
