# Generated by Django 4.2.29 on 2026-04-04 12:23

from django.db import migrations, models


def migrate_aluno_to_usuario(apps, schema_editor):
    Perfil = apps.get_model('core', 'Perfil')
    Perfil.objects.filter(tipo='aluno').update(tipo='usuario')


def migrate_usuario_to_aluno(apps, schema_editor):
    Perfil = apps.get_model('core', 'Perfil')
    Perfil.objects.filter(tipo='usuario').update(tipo='aluno')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfil_unique_perfil_matricula_not_blank_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_aluno_to_usuario, migrate_usuario_to_aluno),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('usuario', 'Usuário'),
                    ('funcionario', 'Funcionário'),
                    ('admin', 'Administrador'),
                ],
                default='usuario',
                max_length=15,
            ),
        ),
    ]
