# Generated by Django 4.2.29 on 2026-04-20 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deletar_objetos_encerrados'),
    ]

    def criar_local_outro(apps, schema_editor):
        Local = apps.get_model('core', 'Local')
        Local.objects.get_or_create(nome='Outro', defaults={'predio': ''})

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='core.local', verbose_name='Local'),
        ),
        migrations.RunPython(criar_local_outro, migrations.RunPython.noop),
    ]
