# Generated by Django 4.2.29 on 2026-04-04 12:34

from django.db import migrations, models


def migrate_funcionario_to_usuario(apps, schema_editor):
    Perfil = apps.get_model('core', 'Perfil')
    Perfil.objects.filter(tipo='funcionario').update(tipo='usuario')


def migrate_usuario_to_funcionario(apps, schema_editor):
    Perfil = apps.get_model('core', 'Perfil')
    Perfil.objects.filter(tipo='usuario').update(tipo='funcionario')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_perfil_tipo'),
    ]

    operations = [
        migrations.RunPython(migrate_funcionario_to_usuario, migrate_usuario_to_funcionario),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('usuario', 'Usuário'),
                    ('admin', 'Administrador'),
                ],
                default='usuario',
                max_length=15,
            ),
        ),
    ]
