# Generated by Django 4.2.29 on 2026-04-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_local_obrigatorio_e_outro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('ativo', 'Ativo'), ('devolvido', 'Devolvido')], default='pendente', max_length=15, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='SolicitacaoPosse',
        ),
    ]
