# Generated by Django 4.2.29 on 2026-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfil_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
