# Generated by Django 4.2.29 on 2026-04-20 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_solicitacaoposse_e_reivindicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da ocorrência')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='edicoes/', verbose_name='Nova imagem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria', verbose_name='Categoria')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.local', verbose_name='Local')),
                ('objeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_edicao', to='core.objeto', verbose_name='Objeto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_edicao', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Edição',
                'verbose_name_plural': 'Solicitações de Edição',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
