# Generated by Django 4.2.29 on 2026-04-12 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_perfil_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_verificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Verificação',
                'verbose_name_plural': 'Códigos de Verificação',
            },
        ),
    ]
